### ISSUE TITLE
Escolha da plataforma a utilizar para criação do site

### ISSUE THREAD

**Issue by joelgarciajr84** [valadares-ti/site#1]

**Comment by henrich-m** [comment]
#### Sugestão

[Jekyll](http://jekyllrb.com/)

##### Pontos Positivos:
- Não há banco de dados, todo o site fica no repositório do Github incluindo controle de usuários
- Hospedagem free usando o github pages
- Não tem que ficar gerenciando muita coisa, quem pode contribuir pro repositório vai poder contribuir para o site e etc.
- Incentiva a galera a usar o Git e o Github, menos uma tecnologia para aprender.
- É o normal em vários projetos opensource

##### Pontos Negativos
- Escrever posts utilizando Markdown ( no caso uma linguagem a mais para aprender ).
- Provavelmente seria doloroso 'compilar' o site Jekyll utilizando Windows, já que o Ruby no Windows é um pouco 'complicado'

**Comment by joelgarciajr84** [comment]
### Voto no WordPress

**Comment by janynnegomes** [comment]
#### Sugestão

Self hosted WordPress (http://wordpress.org) 

**Pontos positivos**
- Tem banco de dados
- Fácil edição de conteúdo, já visando o dia em que a comunidade irá crescer e não terá apenas desenvolvedores com habilidades em mardown
- Facilmente podemos adicionar funcionalidades 
- Podemos adicionar plugins de rede social e forum
- Podemos integrar outros serviços

**Pontos negativos**
- A versão hospedada gratuita não deixa adicionar domínio nem plugins

**Comment by henrich-m** [comment]
@devnetgomez Mas iríamos utilizar o wordpress.com ( Gratuito ) ou a ideia é hospedar o WP em algum lugar ? Qual seria o custo disso ? Quem bancaria ?

**Comment by joelgarciajr84** [comment]
- @ViniciusVinna  tem uma revenda [eu acho]

**Comment by joelgarciajr84** [comment]
@henrich-m @devnetgomez  penso que hospedar um WP é melhor do que usar o gratuito (wordpress.com), quanto ao custo, vamos ver com o @ViniciusVinna

**Comment by henrich-m** [comment]
Manda bala no WordPress então :D 

Enviado do meu iPhone

**Comment by joelgarciajr84** [comment]
Pessoal  ficou decidido pelo **WordPress** mesmo?

**Comment by janynnegomes** [comment]
Falta a opnião do @gnuwilliam

**Comment by gnuwilliam** [comment]
Por mim rola o WordPress, também! :+1:

**Comment by ViniciusVinna** [comment]
WordPress

**Comment by joelgarciajr84** [comment]
### Temos um vencedor: :v:  ?

**Comment by janynnegomes** [comment]
Temos, agora vamos acertar o nome

**Comment by valeriosouza** [comment]
WordPress, cheguei cedo? kkkk

**Comment by joelgarciajr84** [comment]
Opa @valeriosouza, decidimos por usar o WordPress self hosted :smile:
