### ISSUE TITLE
Escolha do nome do Projeto/Comunidade

### ISSUE THREAD

**Issue by joelgarciajr84** [valadares-ti/site#2]

**Comment by joelgarciajr84** [comment]
@valadares-ti/owners

**Comment by joelgarciajr84** [comment]
@devnetgomez @gnuwilliam @ViniciusVinna @henrich-m alguma sugestão de nome?

**Comment by ViniciusVinna** [comment]
# Brainstorm do Nome:
- O nome base não pode ser regionalizado, pensando em uma expansão futura, porém suportaria o sufixo relativo a cidade em que o evento está ocorrendo (Front<in>BH, Wordcamp BH e etc).
- O evento e suas respectivas trilhas, abrangem de forma generalista as áreas de TI (Infra, Dev, Design, UX, Marketing Digital).
- O nome precisa sintetizar as ideias e comportamentos comuns à comunidade.

**Comment by henrich-m** [comment]
Concordo com o @ViniciusVinna porem não consigo imaginar um nome que não leve pão de queijo e uai

**Comment by joelgarciajr84** [comment]
- UaiTI  ( Sei que é ridículo )

**Comment by ViniciusVinna** [comment]
Algumas sugestões de acordo com a disponibilidade dos domínios:
ti-talks.org (disponível)
titalks.org (disponível)
codecoffee.org (disponível)
telaazuldamorte.org (disponível)
io-talks.org (disponível)
turingtalks.org (disponível)
tmd-conf.org (disponível) / TMD tecnologia, Marketing, Design

**Comment by joelgarciajr84** [comment]
- ti-talks.org 
- io-alks.org 
- Curti

**Comment by janynnegomes** [comment]
Orra @ViniciusVinna que codefobia é essa "telaazuldamorte.org", galera do C# vai pirar hehehehe

**Comment by janynnegomes** [comment]
- devopsbrz.com.br (tá disponível tbm)

Foi o que deu pra sair dessa minha cabeça hoje

**Comment by janynnegomes** [comment]
devopsbrz.com tbm está disponível

**Comment by joelgarciajr84** [comment]
Ainda não vi aqui a opinião do @gnuwilliam  :question:

**Comment by henrich-m** [comment]
IO-Talks :+1: 

Acho que devemos fechar a issue e começar a trabalhar nas paradas folks.

**Comment by gnuwilliam** [comment]
io-talks é legal

**Comment by joelgarciajr84** [comment]
Todos que concordam com io-talks comentem com :v:

**Comment by joelgarciajr84** [comment]
:v:

**Comment by ViniciusVinna** [comment]
:v:

**Comment by joelgarciajr84** [comment]
Fechou io-talks então pelo que percebo. Posso mudar o nome da organização aqui no :octocat: ?

**Comment by henrich-m** [comment]
Sure!!! :+1:

**Comment by joelgarciajr84** [comment]
Ok com o voto de todos fechamos a issue e mudaremos o nome da organização para io-alks.org

**Comment by marcelobarbosadg87** [comment]
io-talks 0/
